name: Create Release and Publish on NPM
on:
  push:
    tags:
      - '*'

jobs:
  create-release-publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set env
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $GIT_TAG
          echo ${{ env.GIT_TAG }}

      - name: Extract Tag Name
        id: extract_tag_name
        run: echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/}"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run lint && npm run build

      - name: Publish on NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        id: create_release
        uses: actions/create-release@v1
        with:
          release_name: Release ${{ env.GIT_TAG }}
          tag_name: ${{ env.GIT_TAG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
